[workspace]
members = [
    "app",
    "cli",
    "core",
    "net",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[workspace.package]
edition = "2024"

[workspace.dependencies]