# Rust code formatting configuration
# See: https://rust-lang.github.io/rustfmt/

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2024"

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments and documentation
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 80
