# rustfmt.toml (compatible stable)

max_width = 100
reorder_imports = true

trailing_comma = "Vertical"

format_strings = true
format_macro_bodies = true

reorder_modules = true
reorder_impl_items = true

where_single_line = false

blank_lines_upper_bound = 2

unstable_features = false

fn_params_layout = "Tall"
